version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: './apps/api/Dockerfile'
    ports:
      - 8000:8000
    volumes:
      - ./apps/api:/usr/src/app
    env_file:
      - ./.env